### ISSUE TITLE
Feature request: convert positional arguments to environment variables

### ISSUE THREAD

**Issue by wabiloo** [bukalapak/vanadia#2]
It would be useful to have the option to convert REST arguments in the URL.
For example:
https://api.myservice.com/v1/object/:id/type
would become 
https://api.myservice.com/v1/object/{{id}}/type

**Comment by budipang** [comment]
Hi @wabiloo , from your given example, I think `:id` will be more appropriate than `{{id}}` since `:id` is adjustable from params while `{{id}}` is from environment variables. We already support both type accordingly.
